name: app_arbitro
description: "SGEU - Aplicação de Arbitragem com Sincronização Offline."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.8 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- BANCO DE DADOS (PERSISTÊNCIA LOCAL) ---
  sqflite: ^2.3.0
  path: ^1.9.0

  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0

  # --- COMUNICAÇÃO COM API (SPRING BOOT) ---
  http: ^1.1.0

  # --- INTERFACE E ÍCONES ---
  cupertino_icons: ^1.0.8

  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.2
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints recomendados para manter o código limpo
  flutter_lints: ^3.0.0

flutter:
  # Garante que os ícones do Material (golo, cartões, pause) funcionem
  uses-material-design: true

  # Caso decida adicionar imagens ou fontes customizadas futuramente:
  # assets:
  #   - assets/images/